package me.craftymcfish.nomorehorses.villager;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import me.craftymcfish.nomorehorses.registry.ModItems;
import net.fabricmc.fabric.api.object.builder.v1.trade.TradeOfferHelper;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.entity.Entity;
import net.minecraft.item.Item;
import net.minecraft.item.ItemConvertible;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.potion.Potions;
import net.minecraft.util.math.random.Random;
import net.minecraft.village.TradeOffer;
import net.minecraft.village.TradeOfferList;
import net.minecraft.village.TradeOffers;
import org.apache.commons.lang3.tuple.Pair;

import java.util.List;

public class WanderingCollectorTrades {
    public static final Int2ObjectMap<TradeOffers.Factory[]> WANDERING_COLLECTOR_TRADES = WanderingCollectorTrades.copyToFastUtilMap(ImmutableMap.of(
            1, new TradeOffers.Factory[]{
                    buyItemFactory(Items.STONE, 16, 1),
                    buyItemFactory(Items.GRANITE, 16, 1),
                    buyItemFactory(Items.POLISHED_GRANITE, 16, 1),
                    buyItemFactory(Items.DIORITE, 16, 1),
                    buyItemFactory(Items.POLISHED_DIORITE, 16, 1),
                    buyItemFactory(Items.ANDESITE, 16, 1),
                    buyItemFactory(Items.POLISHED_ANDESITE, 16, 1),
                    buyItemFactory(Items.GRASS_BLOCK, 16, 1),
                    buyItemFactory(Items.DIRT, 16, 1),
                    buyItemFactory(Items.COARSE_DIRT, 16, 1),
                    buyItemFactory(Items.PODZOL, 16, 1),
                    buyItemFactory(Items.COBBLESTONE, 16, 1),
                    buyItemFactory(Items.OAK_PLANKS, 16, 1),
                    buyItemFactory(Items.SPRUCE_PLANKS, 16, 1),
                    buyItemFactory(Items.BIRCH_PLANKS, 16, 1),
                    buyItemFactory(Items.JUNGLE_PLANKS, 16, 1),
                    buyItemFactory(Items.ACACIA_PLANKS, 16, 1),
                    buyItemFactory(Items.DARK_OAK_PLANKS, 16, 1),
                    buyItemFactory(Items.OAK_SAPLING, 16, 1),
                    buyItemFactory(Items.SPRUCE_SAPLING, 16, 1),
                    buyItemFactory(Items.BIRCH_SAPLING, 16, 1),
                    buyItemFactory(Items.JUNGLE_SAPLING, 16, 1),
                    buyItemFactory(Items.ACACIA_SAPLING, 16, 1),
                    buyItemFactory(Items.DARK_OAK_SAPLING, 16, 1),
                    buyItemFactory(Items.SAND, 16, 1),
                    buyItemFactory(Items.RED_SAND, 16, 1),
                    buyItemFactory(Items.GRAVEL, 16, 1),
                    buyItemFactory(Items.OAK_LOG, 16, 1),
                    buyItemFactory(Items.SPRUCE_LOG, 16, 1),
                    buyItemFactory(Items.BIRCH_LOG, 16, 1),
                    buyItemFactory(Items.JUNGLE_LOG, 16, 1),
                    buyItemFactory(Items.ACACIA_LOG, 16, 1),
                    buyItemFactory(Items.DARK_OAK_LOG, 16, 1),
                    buyItemFactory(Items.STRIPPED_SPRUCE_LOG, 16, 1),
                    buyItemFactory(Items.STRIPPED_BIRCH_LOG, 16, 1),
                    buyItemFactory(Items.STRIPPED_JUNGLE_LOG, 16, 1),
                    buyItemFactory(Items.STRIPPED_ACACIA_LOG, 16, 1),
                    buyItemFactory(Items.STRIPPED_DARK_OAK_LOG, 16, 1),
                    buyItemFactory(Items.STRIPPED_OAK_LOG, 16, 1),
                    buyItemFactory(Items.OAK_WOOD, 16, 1),
                    buyItemFactory(Items.SPRUCE_WOOD, 16, 1),
                    buyItemFactory(Items.BIRCH_WOOD, 16, 1),
                    buyItemFactory(Items.JUNGLE_WOOD, 16, 1),
                    buyItemFactory(Items.ACACIA_WOOD, 16, 1),
                    buyItemFactory(Items.DARK_OAK_WOOD, 16, 1),
                    buyItemFactory(Items.STRIPPED_OAK_WOOD, 16, 1),
                    buyItemFactory(Items.STRIPPED_SPRUCE_WOOD, 16, 1),
                    buyItemFactory(Items.STRIPPED_BIRCH_WOOD, 16, 1),
                    buyItemFactory(Items.STRIPPED_JUNGLE_WOOD, 16, 1),
                    buyItemFactory(Items.STRIPPED_ACACIA_WOOD, 16, 1),
                    buyItemFactory(Items.STRIPPED_DARK_OAK_WOOD, 16, 1),
                    buyItemFactory(Items.OAK_LEAVES, 16, 1),
                    buyItemFactory(Items.SPRUCE_LEAVES, 16, 1),
                    buyItemFactory(Items.BIRCH_LEAVES, 16, 1),
                    buyItemFactory(Items.JUNGLE_LEAVES, 16, 1),
                    buyItemFactory(Items.ACACIA_LEAVES, 16, 1),
                    buyItemFactory(Items.DARK_OAK_LEAVES, 16, 1),
                    buyItemFactory(Items.AZALEA_LEAVES, 16, 1),
                    buyItemFactory(Items.FLOWERING_AZALEA_LEAVES, 16, 1),
                    buyItemFactory(Items.SPONGE, 1, 1),
                    buyItemFactory(Items.WET_SPONGE, 1, 1),
                    buyItemFactory(Items.GLASS, 16, 1),
                    buyItemFactory(Items.DISPENSER, 1, 1),
                    buyItemFactory(Items.SANDSTONE, 16, 1),
                    buyItemFactory(Items.CHISELED_SANDSTONE, 16, 1),
                    buyItemFactory(Items.CUT_SANDSTONE, 16, 1),
                    buyItemFactory(Items.NOTE_BLOCK, 8, 1),
                    buyItemFactory(Items.POWERED_RAIL, 8, 1),
                    buyItemFactory(Items.DETECTOR_RAIL, 8, 1),
                    buyItemFactory(Items.STICKY_PISTON, 4, 1),
                    buyItemFactory(Items.COBWEB, 8, 1),
                    buyItemFactory(Items.GRASS, 8, 1),
                    buyItemFactory(Items.FERN, 8, 1),
                    buyItemFactory(Items.DEAD_BUSH, 8, 1),
                    buyItemFactory(Items.SEAGRASS, 8, 1),
                    buyItemFactory(Items.PISTON, 8, 1),
                    buyItemFactory(Items.WHITE_WOOL, 16, 1),
                    buyItemFactory(Items.ORANGE_WOOL, 16, 1),
                    buyItemFactory(Items.MAGENTA_WOOL, 16, 1),
                    buyItemFactory(Items.LIGHT_BLUE_WOOL, 16, 1),
                    buyItemFactory(Items.YELLOW_WOOL, 16, 1),
                    buyItemFactory(Items.LIME_WOOL, 16, 1),
                    buyItemFactory(Items.PINK_WOOL, 16, 1),
                    buyItemFactory(Items.GRAY_WOOL, 16, 1),
                    buyItemFactory(Items.LIGHT_GRAY_WOOL, 16, 1),
                    buyItemFactory(Items.CYAN_WOOL, 16, 1),
                    buyItemFactory(Items.PURPLE_WOOL, 16, 1),
                    buyItemFactory(Items.BLUE_WOOL, 16, 1),
                    buyItemFactory(Items.BROWN_WOOL, 16, 1),
                    buyItemFactory(Items.GREEN_WOOL, 16, 1),
                    buyItemFactory(Items.RED_WOOL, 16, 1),
                    buyItemFactory(Items.BLACK_WOOL, 16, 1),
                    buyItemFactory(Items.DANDELION, 16, 1),
                    buyItemFactory(Items.POPPY, 16, 1),
                    buyItemFactory(Items.BLUE_ORCHID, 16, 1),
                    buyItemFactory(Items.ALLIUM, 16, 1),
                    buyItemFactory(Items.AZURE_BLUET, 16, 1),
                    buyItemFactory(Items.RED_TULIP, 16, 1),
                    buyItemFactory(Items.ORANGE_TULIP, 16, 1),
                    buyItemFactory(Items.WHITE_TULIP, 16, 1),
                    buyItemFactory(Items.PINK_TULIP, 16, 1),
                    buyItemFactory(Items.OXEYE_DAISY, 16, 1),
                    buyItemFactory(Items.CORNFLOWER, 16, 1),
                    buyItemFactory(Items.WITHER_ROSE, 16, 1),
                    buyItemFactory(Items.LILY_OF_THE_VALLEY, 16, 1),
                    buyItemFactory(Items.BROWN_MUSHROOM, 16, 1),
                    buyItemFactory(Items.RED_MUSHROOM, 16, 1),
                    buyItemFactory(Items.BRICKS, 8, 1),
                    buyItemFactory(Items.TNT, 4, 1),
                    buyItemFactory(Items.BOOKSHELF, 16, 1),
                    buyItemFactory(Items.MOSSY_COBBLESTONE, 8, 1),
                    buyItemFactory(Items.OBSIDIAN, 16, 1),
                    buyItemFactory(Items.TORCH, 16, 1),
                    buyItemFactory(Items.CHEST, 16, 1),
                    buyItemFactory(Items.CRAFTING_TABLE, 16, 1),
                    buyItemFactory(Items.FURNACE, 8, 1),
                    buyItemFactory(Items.LADDER, 16, 1),
                    buyItemFactory(Items.RAIL, 8, 1),
                    buyItemFactory(Items.LEVER, 4, 1),
                    buyItemFactory(Items.REDSTONE_TORCH, 8, 1),
                    buyItemFactory(Items.ICE, 16, 1),
                    buyItemFactory(Items.SNOW_BLOCK, 16, 1),
                    buyItemFactory(Items.CACTUS, 16, 1),
                    buyItemFactory(Items.CLAY, 16, 1),
                    buyItemFactory(Items.SUGAR_CANE, 16, 1),
                    buyItemFactory(Items.JUKEBOX, 1, 1),
                    buyItemFactory(Items.PUMPKIN, 16, 1),
                    buyItemFactory(Items.NETHERRACK, 16, 1),
                    buyItemFactory(Items.SOUL_SAND, 16, 1),
                    buyItemFactory(Items.SOUL_SOIL, 16, 1),
                    buyItemFactory(Items.BASALT, 16, 1),
                    buyItemFactory(Items.POLISHED_BASALT, 16, 1),
                    buyItemFactory(Items.SOUL_TORCH, 16, 1),
                    buyItemFactory(Items.GLOWSTONE, 16, 1),
                    buyItemFactory(Items.CARVED_PUMPKIN, 4, 1),
                    buyItemFactory(Items.JACK_O_LANTERN, 4, 1),
                    buyItemFactory(Items.CAKE, 1, 1),
                    buyItemFactory(Items.REPEATER, 4, 1),
                    buyItemFactory(Items.WHITE_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.ORANGE_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.MAGENTA_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.LIGHT_BLUE_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.YELLOW_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.LIME_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.PINK_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.GRAY_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.LIGHT_GRAY_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.CYAN_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.PURPLE_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.BLUE_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.BROWN_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.GREEN_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.RED_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.BLACK_STAINED_GLASS, 16, 1),
                    buyItemFactory(Items.STONE_BRICKS, 16, 1),
                    buyItemFactory(Items.MOSSY_STONE_BRICKS, 16, 1),
                    buyItemFactory(Items.CRACKED_STONE_BRICKS, 16, 1),
                    buyItemFactory(Items.CHISELED_STONE_BRICKS, 16, 1),
                    buyItemFactory(Items.BROWN_MUSHROOM_BLOCK, 16, 1),
                    buyItemFactory(Items.RED_MUSHROOM_BLOCK, 16, 1),
                    buyItemFactory(Items.MUSHROOM_STEM, 16, 1),
                    buyItemFactory(Items.IRON_BARS, 16, 1),
                    buyItemFactory(Items.CHAIN, 4, 1),
                    buyItemFactory(Items.GLASS_PANE, 16, 1),
                    buyItemFactory(Items.MELON, 16, 1),
                    buyItemFactory(Items.VINE, 8, 1),
                    buyItemFactory(Items.GLOW_LICHEN, 4, 1),
                    buyItemFactory(Items.MYCELIUM, 8, 1),
                    buyItemFactory(Items.LILY_PAD, 16, 1),
                    buyItemFactory(Items.NETHER_BRICKS, 16, 1),
                    buyItemFactory(Items.ENCHANTING_TABLE, 1, 1),
                    buyItemFactory(Items.BREWING_STAND, 1, 1),
                    buyItemFactory(Items.CAULDRON, 1, 1),
                    buyItemFactory(Items.END_STONE, 16, 1),
                    buyItemFactory(Items.REDSTONE_LAMP, 4, 1),
                    buyItemFactory(Items.ENDER_CHEST, 1, 1),
                    buyItemFactory(Items.TRIPWIRE_HOOK, 4, 1),
                    buyItemFactory(Items.FLOWER_POT, 4, 1),
                    buyItemFactory(Items.WITHER_SKELETON_SKULL, 1, 4),
                    buyItemFactory(Items.DRAGON_HEAD, 1, 8),
                    buyItemFactory(Items.ANVIL, 1, 1),
                    buyItemFactory(Items.COMPARATOR, 2, 1),
                    buyItemFactory(Items.DAYLIGHT_DETECTOR, 4, 1),
                    buyItemFactory(Items.HOPPER, 1, 1),
                    buyItemFactory(Items.CHISELED_QUARTZ_BLOCK, 4, 1),
                    buyItemFactory(Items.QUARTZ_PILLAR, 4, 1),
                    buyItemFactory(Items.ACTIVATOR_RAIL, 4, 1),
                    buyItemFactory(Items.DROPPER, 4, 1),
                    buyItemFactory(Items.WHITE_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.ORANGE_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.MAGENTA_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.LIGHT_BLUE_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.YELLOW_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.LIME_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.PINK_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.GRAY_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.LIGHT_GRAY_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.CYAN_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.PURPLE_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.BLUE_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.BROWN_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.GREEN_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.RED_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.BLACK_TERRACOTTA, 16, 1),
                    buyItemFactory(Items.SLIME_BLOCK, 1, 1),
                    buyItemFactory(Items.PRISMARINE, 8, 1),
                    buyItemFactory(Items.PRISMARINE_BRICKS, 8, 1),
                    buyItemFactory(Items.DARK_PRISMARINE, 4, 1),
                    buyItemFactory(Items.SEA_LANTERN, 2, 1),
                    buyItemFactory(Items.HAY_BLOCK, 2, 1),
                    buyItemFactory(Items.TERRACOTTA, 16, 1),
                    buyItemFactory(Items.PACKED_ICE, 8, 1),
                    buyItemFactory(Items.SUNFLOWER, 1, 1),
                    buyItemFactory(Items.LILAC, 1, 1),
                    buyItemFactory(Items.ROSE_BUSH, 1, 1),
                    buyItemFactory(Items.PEONY, 1, 1),
                    buyItemFactory(Items.TALL_GRASS, 4, 1),
                    buyItemFactory(Items.LARGE_FERN, 4, 1),
                    buyItemFactory(Items.RED_SANDSTONE, 4, 1),
                    buyItemFactory(Items.CHISELED_RED_SANDSTONE, 4, 1),
                    buyItemFactory(Items.CUT_RED_SANDSTONE, 4, 1),
                    buyItemFactory(Items.SMOOTH_STONE, 8, 1),
                    buyItemFactory(Items.SMOOTH_SANDSTONE, 8, 1),
                    buyItemFactory(Items.SMOOTH_QUARTZ, 4, 1),
                    buyItemFactory(Items.SMOOTH_RED_SANDSTONE, 4, 1),
                    buyItemFactory(Items.END_ROD, 8, 1),
                    buyItemFactory(Items.CHORUS_FLOWER, 2, 1),
                    buyItemFactory(Items.PURPUR_BLOCK, 8, 1),
                    buyItemFactory(Items.PURPUR_PILLAR, 8, 1),
                    buyItemFactory(Items.END_STONE_BRICKS, 8, 1),
                    buyItemFactory(Items.MAGMA_BLOCK, 16, 1),
                    buyItemFactory(Items.NETHER_WART_BLOCK, 16, 1),
                    buyItemFactory(Items.RED_NETHER_BRICKS, 16, 1),
                    buyItemFactory(Items.BONE_BLOCK, 8, 1),
                    buyItemFactory(Items.OBSERVER, 1, 1),
                    buyItemFactory(Items.WHITE_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.ORANGE_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.MAGENTA_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.LIGHT_BLUE_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.YELLOW_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.LIME_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.PINK_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.GRAY_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.LIGHT_GRAY_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.CYAN_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.PURPLE_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.BLUE_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.BROWN_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.GREEN_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.RED_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.BLACK_GLAZED_TERRACOTTA, 4, 1),
                    buyItemFactory(Items.WHITE_CONCRETE, 8, 1),
                    buyItemFactory(Items.ORANGE_CONCRETE, 8, 1),
                    buyItemFactory(Items.MAGENTA_CONCRETE, 8, 1),
                    buyItemFactory(Items.LIGHT_BLUE_CONCRETE, 8, 1),
                    buyItemFactory(Items.YELLOW_CONCRETE, 8, 1),
                    buyItemFactory(Items.LIME_CONCRETE, 8, 1),
                    buyItemFactory(Items.PINK_CONCRETE, 8, 1),
                    buyItemFactory(Items.GRAY_CONCRETE, 8, 1),
                    buyItemFactory(Items.LIGHT_GRAY_CONCRETE, 8, 1),
                    buyItemFactory(Items.CYAN_CONCRETE, 8, 1),
                    buyItemFactory(Items.PURPLE_CONCRETE, 8, 1),
                    buyItemFactory(Items.BLUE_CONCRETE, 8, 1),
                    buyItemFactory(Items.BROWN_CONCRETE, 8, 1),
                    buyItemFactory(Items.GREEN_CONCRETE, 8, 1),
                    buyItemFactory(Items.RED_CONCRETE, 8, 1),
                    buyItemFactory(Items.BLACK_CONCRETE, 8, 1),
                    buyItemFactory(Items.WHITE_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.ORANGE_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.MAGENTA_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.LIGHT_BLUE_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.YELLOW_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.LIME_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.PINK_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.GRAY_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.LIGHT_GRAY_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.CYAN_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.PURPLE_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.BLUE_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.BROWN_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.GREEN_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.RED_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.BLACK_CONCRETE_POWDER, 8, 1),
                    buyItemFactory(Items.KELP, 16, 1),
                    buyItemFactory(Items.DRIED_KELP_BLOCK, 4, 1),
                    buyItemFactory(Items.TURTLE_EGG, 1, 1),
                    buyItemFactory(Items.DEAD_TUBE_CORAL_BLOCK, 4, 1),
                    buyItemFactory(Items.DEAD_BRAIN_CORAL_BLOCK, 4, 1),
                    buyItemFactory(Items.DEAD_BUBBLE_CORAL_BLOCK, 4, 1),
                    buyItemFactory(Items.DEAD_FIRE_CORAL_BLOCK, 4, 1),
                    buyItemFactory(Items.DEAD_HORN_CORAL_BLOCK, 4, 1),
                    buyItemFactory(Items.TUBE_CORAL_BLOCK, 4, 1),
                    buyItemFactory(Items.BRAIN_CORAL_BLOCK, 4, 1),
                    buyItemFactory(Items.BUBBLE_CORAL_BLOCK, 4, 1),
                    buyItemFactory(Items.FIRE_CORAL_BLOCK, 4, 1),
                    buyItemFactory(Items.HORN_CORAL_BLOCK, 4, 1),
                    buyItemFactory(Items.DEAD_TUBE_CORAL, 4, 1),
                    buyItemFactory(Items.DEAD_BRAIN_CORAL, 4, 1),
                    buyItemFactory(Items.DEAD_BUBBLE_CORAL, 4, 1),
                    buyItemFactory(Items.DEAD_FIRE_CORAL, 4, 1),
                    buyItemFactory(Items.DEAD_HORN_CORAL, 4, 1),
                    buyItemFactory(Items.TUBE_CORAL, 4, 1),
                    buyItemFactory(Items.BRAIN_CORAL, 4, 1),
                    buyItemFactory(Items.BUBBLE_CORAL, 4, 1),
                    buyItemFactory(Items.FIRE_CORAL, 4, 1),
                    buyItemFactory(Items.HORN_CORAL, 4, 1),
                    buyItemFactory(Items.DEAD_TUBE_CORAL_FAN, 4, 1),
                    buyItemFactory(Items.DEAD_BRAIN_CORAL_FAN, 4, 1),
                    buyItemFactory(Items.DEAD_BUBBLE_CORAL_FAN, 4, 1),
                    buyItemFactory(Items.DEAD_FIRE_CORAL_FAN, 4, 1),
                    buyItemFactory(Items.DEAD_HORN_CORAL_FAN, 4, 1),
                    buyItemFactory(Items.TUBE_CORAL_FAN, 4, 1),
                    buyItemFactory(Items.BRAIN_CORAL_FAN, 4, 1),
                    buyItemFactory(Items.BUBBLE_CORAL_FAN, 4, 1),
                    buyItemFactory(Items.FIRE_CORAL_FAN, 4, 1),
                    buyItemFactory(Items.HORN_CORAL_FAN, 4, 1),
                    buyItemFactory(Items.SEA_PICKLE, 8, 1),
                    buyItemFactory(Items.BLUE_ICE, 2, 1),
                    buyItemFactory(Items.BAMBOO, 16, 1),
                    buyItemFactory(Items.SCAFFOLDING, 16, 1),
                    buyItemFactory(Items.LOOM, 1, 1),
                    buyItemFactory(Items.BARREL, 1, 1),
                    buyItemFactory(Items.SMOKER, 1, 1),
                    buyItemFactory(Items.BLAST_FURNACE, 1, 1),
                    buyItemFactory(Items.CARTOGRAPHY_TABLE, 1, 1),
                    buyItemFactory(Items.FLETCHING_TABLE, 1, 1),
                    buyItemFactory(Items.GRINDSTONE, 1, 1),
                    buyItemFactory(Items.LECTERN, 1, 1),
                    buyItemFactory(Items.SMITHING_TABLE, 1, 1),
                    buyItemFactory(Items.STONECUTTER, 1, 1),
                    buyItemFactory(Items.BELL, 1, 1),
                    buyItemFactory(Items.LANTERN, 4, 1),
                    buyItemFactory(Items.SOUL_LANTERN, 4, 1),
                    buyItemFactory(Items.CAMPFIRE, 1, 1),
                    buyItemFactory(Items.SOUL_CAMPFIRE, 1, 1),
                    buyItemFactory(Items.WARPED_STEM, 16, 1),
                    buyItemFactory(Items.STRIPPED_WARPED_STEM, 16, 1),
                    buyItemFactory(Items.WARPED_HYPHAE, 16, 1),
                    buyItemFactory(Items.STRIPPED_WARPED_HYPHAE, 16, 1),
                    buyItemFactory(Items.WARPED_NYLIUM, 16, 1),
                    buyItemFactory(Items.WARPED_FUNGUS, 16, 1),
                    buyItemFactory(Items.WARPED_WART_BLOCK, 16, 1),
                    buyItemFactory(Items.WARPED_ROOTS, 16, 1),
                    buyItemFactory(Items.NETHER_SPROUTS, 16, 1),
                    buyItemFactory(Items.CRIMSON_STEM, 16, 1),
                    buyItemFactory(Items.STRIPPED_CRIMSON_STEM, 16, 1),
                    buyItemFactory(Items.CRIMSON_HYPHAE, 16, 1),
                    buyItemFactory(Items.STRIPPED_CRIMSON_HYPHAE, 16, 1),
                    buyItemFactory(Items.CRIMSON_NYLIUM, 16, 1),
                    buyItemFactory(Items.CRIMSON_FUNGUS, 16, 1),
                    buyItemFactory(Items.SHROOMLIGHT, 16, 1),
                    buyItemFactory(Items.WEEPING_VINES, 16, 1),
                    buyItemFactory(Items.TWISTING_VINES, 16, 1),
                    buyItemFactory(Items.CRIMSON_ROOTS, 16, 1),
                    buyItemFactory(Items.CRIMSON_PLANKS, 16, 1),
                    buyItemFactory(Items.WARPED_PLANKS, 16, 1),
                    buyItemFactory(Items.COMPOSTER, 1, 1),
                    buyItemFactory(Items.TARGET, 1, 1),
                    buyItemFactory(Items.BEE_NEST, 1, 1),
                    buyItemFactory(Items.BEEHIVE, 1, 1),
                    buyItemFactory(Items.HONEY_BLOCK, 8, 1),
                    buyItemFactory(Items.HONEYCOMB_BLOCK, 8, 1),
                    buyItemFactory(Items.CRYING_OBSIDIAN, 8, 1),
                    buyItemFactory(Items.RESPAWN_ANCHOR, 2, 1),
                    buyItemFactory(Items.LODESTONE, 1, 1),
                    buyItemFactory(Items.BLACKSTONE, 16, 1),
                    buyItemFactory(Items.POLISHED_BLACKSTONE, 16, 1),
                    buyItemFactory(Items.POLISHED_BLACKSTONE_BRICKS, 16, 1),
                    buyItemFactory(Items.CRACKED_POLISHED_BLACKSTONE_BRICKS, 16, 1),
                    buyItemFactory(Items.CHISELED_POLISHED_BLACKSTONE, 16, 1),
                    buyItemFactory(Items.GILDED_BLACKSTONE, 2, 1),
                    buyItemFactory(Items.CHISELED_NETHER_BRICKS, 16, 1),
                    buyItemFactory(Items.CRACKED_NETHER_BRICKS, 16, 1),
                    buyItemFactory(Items.QUARTZ_BRICKS, 4, 1),
                    buyItemFactory(Items.AMETHYST_BLOCK, 4, 1),
                    buyItemFactory(Items.TUFF, 16, 1),
                    buyItemFactory(Items.CALCITE, 16, 1),
                    buyItemFactory(Items.TINTED_GLASS, 8, 1),
                    buyItemFactory(Items.SCULK_SENSOR, 2, 1),
                    buyItemFactory(Items.OXIDIZED_COPPER, 16, 1),
                    buyItemFactory(Items.WEATHERED_COPPER, 16, 1),
                    buyItemFactory(Items.EXPOSED_COPPER, 16, 1),
                    buyItemFactory(Items.COPPER_BLOCK, 16, 1),
                    buyItemFactory(Items.OXIDIZED_CUT_COPPER, 16, 1),
                    buyItemFactory(Items.WEATHERED_CUT_COPPER, 16, 1),
                    buyItemFactory(Items.EXPOSED_CUT_COPPER, 16, 1),
                    buyItemFactory(Items.CUT_COPPER, 16, 1),
                    buyItemFactory(Items.WAXED_COPPER_BLOCK, 16, 1),
                    buyItemFactory(Items.WAXED_WEATHERED_COPPER, 16, 1),
                    buyItemFactory(Items.WAXED_EXPOSED_COPPER, 16, 1),
                    buyItemFactory(Items.WAXED_OXIDIZED_COPPER, 16, 1),
                    buyItemFactory(Items.WAXED_OXIDIZED_CUT_COPPER, 16, 1),
                    buyItemFactory(Items.WAXED_WEATHERED_CUT_COPPER, 16, 1),
                    buyItemFactory(Items.WAXED_EXPOSED_CUT_COPPER, 16, 1),
                    buyItemFactory(Items.WAXED_CUT_COPPER, 16, 1),
                    buyItemFactory(Items.LIGHTNING_ROD, 1, 1),
                    buyItemFactory(Items.POINTED_DRIPSTONE, 16, 1),
                    buyItemFactory(Items.DRIPSTONE_BLOCK, 8, 1),
                    buyItemFactory(Items.SPORE_BLOSSOM, 1, 1),
                    buyItemFactory(Items.AZALEA, 4, 1),
                    buyItemFactory(Items.FLOWERING_AZALEA, 4, 1),
                    buyItemFactory(Items.MOSS_CARPET, 4, 1),
                    buyItemFactory(Items.MOSS_BLOCK, 16, 1),
                    buyItemFactory(Items.BIG_DRIPLEAF, 4, 1),
                    buyItemFactory(Items.SMALL_DRIPLEAF, 4, 1),
                    buyItemFactory(Items.HANGING_ROOTS, 4, 1),
                    buyItemFactory(Items.ROOTED_DIRT, 8, 1),
                    buyItemFactory(Items.DEEPSLATE, 16, 1),
                    buyItemFactory(Items.COBBLED_DEEPSLATE, 16, 1),
                    buyItemFactory(Items.POLISHED_DEEPSLATE, 16, 1),
                    buyItemFactory(Items.DEEPSLATE_TILES, 16, 1),
                    buyItemFactory(Items.DEEPSLATE_BRICKS, 16, 1),
                    buyItemFactory(Items.CHISELED_DEEPSLATE, 16, 1),
                    buyItemFactory(Items.CRACKED_DEEPSLATE_BRICKS, 16, 1),
                    buyItemFactory(Items.CRACKED_DEEPSLATE_TILES, 16, 1),
                    buyItemFactory(Items.SMOOTH_BASALT, 16, 1),
                    buyItemFactory(Items.MUD, 16, 1),
                    buyItemFactory(Items.BAMBOO_BLOCK, 16, 1),
                    buyItemFactory(Items.BAMBOO_PLANKS, 16, 1),
                    buyItemFactory(Items.STRIPPED_BAMBOO_BLOCK, 16, 1),
                    buyItemFactory(Items.STRIPPED_BAMBOO_BLOCK, 16, 1),
            },
            2, new TradeOffers.Factory[]{
                    buyItemFactory(Items.EMERALD_ORE, 1, 1),
                    buyItemFactory(Items.DEEPSLATE_EMERALD_ORE, 1, 1),
                    buyItemFactory(Items.EMERALD_BLOCK, 1, 1),

                    buyItemFactory(Items.COPPER_ORE, 16, 1),
                    buyItemFactory(Items.DEEPSLATE_COPPER_ORE, 16, 1),
                    buyItemFactory(Items.RAW_COPPER_BLOCK, 8, 1),

                    buyItemFactory(Items.NETHER_QUARTZ_ORE, 4, 1),
                    buyItemFactory(Items.QUARTZ_BLOCK, 4, 1),

                    buyItemFactory(Items.REDSTONE_ORE, 8, 1),
                    buyItemFactory(Items.DEEPSLATE_REDSTONE_ORE, 8, 1),
                    buyItemFactory(Items.REDSTONE_BLOCK, 4, 1),

                    buyItemFactory(Items.LAPIS_ORE, 4, 1),
                    buyItemFactory(Items.DEEPSLATE_LAPIS_ORE, 4, 1),
                    buyItemFactory(Items.LAPIS_BLOCK, 2, 1),

                    buyItemFactory(Items.GOLD_ORE, 4, 1),
                    buyItemFactory(Items.DEEPSLATE_GOLD_ORE, 4, 1),
                    buyItemFactory(Items.RAW_GOLD_BLOCK, 1, 1),
                    buyItemFactory(Items.GOLD_BLOCK, 1, 1),
                    buyItemFactory(Items.NETHER_GOLD_ORE, 4, 1),

                    buyItemFactory(Items.IRON_ORE, 16, 1),
                    buyItemFactory(Items.DEEPSLATE_IRON_ORE, 16, 1),
                    buyItemFactory(Items.RAW_IRON_BLOCK, 16, 1),
                    buyItemFactory(Items.IRON_BLOCK, 16, 1),

                    buyItemFactory(Items.COAL_ORE, 4, 1),
                    buyItemFactory(Items.DEEPSLATE_COAL_ORE, 1, 1),
                    buyItemFactory(Items.COAL_BLOCK, 4, 1),

                    buyItemFactory(Items.DIAMOND_ORE, 1, 1),
                    buyItemFactory(Items.DEEPSLATE_DIAMOND_ORE, 1, 1),
                    buyItemFactory(Items.DIAMOND_BLOCK, 1, 1),

                    buyItemFactory(Items.NETHERITE_BLOCK, 1, 8),
                    buyItemFactory(Items.ANCIENT_DEBRIS, 1, 2),
            }));


    private static Int2ObjectMap<TradeOffers.Factory[]> copyToFastUtilMap(ImmutableMap<Integer, TradeOffers.Factory[]> map) {
        return new Int2ObjectOpenHashMap<TradeOffers.Factory[]>(map);
    }

    private static BuyItemFactory buyItemFactory(Item buyItem, int itemCount) {
        return buyItemFactory(buyItem, itemCount, 1, 5, 1);
    }

    private static BuyItemFactory buyItemFactory(Item buyItem, int itemCount, int money) {
        return buyItemFactory(buyItem, itemCount, 1, 5, money);
    }

    private static BuyItemFactory buyItemFactory(Item buyItem, int itemCount, int experience, int money) {
        return buyItemFactory(buyItem, itemCount, 1, experience, money);
    }
    private static BuyItemFactory buyItemFactory(Item buyItem, int itemCount, int maxUses, int experience, int money) {
        return new WanderingCollectorTrades.BuyItemFactory(buyItem, itemCount, maxUses, experience, money);
    }

    public static class BuyItemFactory
            implements TradeOffers.Factory {
        private final ItemStack stack;
        private final int maxUses;
        private final int experience;
        private final int price;
        private final float multiplier;

        public BuyItemFactory(ItemConvertible item, int count, int maxUses, int experience) {
            this(item, count, maxUses, experience, 1);
        }

        public BuyItemFactory(ItemConvertible item, int count, int maxUses, int experience, int price) {
            this(new ItemStack(item.asItem(), count), maxUses, experience, price);
        }

        public BuyItemFactory(ItemStack stack, int maxUses, int experience, int price) {
            this.stack = stack;
            this.maxUses = maxUses;
            this.experience = experience;
            this.price = price;
            this.multiplier = 0.05f;
        }

        @Override
        public TradeOffer create(Entity entity, Random random) {
            return new TradeOffer(this.stack.copy(), new ItemStack(ModItems.MONEY, this.price), this.maxUses, this.experience, this.multiplier);
        }
    }
}
